import AuthProvider from "@/components/AuthProvider/AuthProvider";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navabar/Navbar";
import { ThemeProvider } from "@/context/ThemContext";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alex project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className='container'>
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
